name = "HyperbolicSemanticNetworks"
version = "0.1.0"

[deps]
# Graph libraries
LightGraphs = "093fc24a-ae57-5d19-3b6c-3b3d5c3b3b3b"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
GraphPlot = "a2cc645f-0e6a-5fcd-8719-6d5c9610ff09"

# Data handling
DataFrames = "a93c6f00-e57d-5684-b7b6-d819539f2c03"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf12d14"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Parquet = "7c8665c4-4981-4a7a-8a5c-9b8ad1c7b1c4"

# Numerical computation
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ece69a1a9"

# Optimization and ML
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Clustering = "aaaa29a8-35af-508c-8bc3-b66a8aab2d75"

# Visualization
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

# Parallel processing
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f12b6c0"

# Utilities
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ArgParse = "c7e460c6-2fb9-53a9-8e5b-351d84e6ebf1"
Logging = "56ddb016-857b-54e1-b83d-7f0d3b5c5c5c"

# Testing
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Coverage = "a2441757-f6aa-5e54-8b26-5dfb6845a4c0"
BenchmarkTools = "1.3.1"  # Version for performance testing

# FFI for Rust
Libdl = "8f399da3-3557-5675-b5ff-9c8455922d7c"

[compat]
julia = "1.9"
